spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: test_password
  jpa:
    hibernate:
      ddl-auto: update # Ou 'none' se você usar scripts para criar o esquema nos testes
    show-sql: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # O Eureka server não é acessível pelo nome de serviço no ambiente do job 'test' do GitHub Actions, apenas 'localhost'
