version: '3.8'

services:
  discovery-server:
    build: ./microsservices_esofii/discovery-server
    ports:
      - "8761:8761"
    networks:
      - spring-net

  config-server:
    build: ./microsservices_esofii/config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - spring-net

  criar-usuarios:
    build: ./config-service/criar-usuarios
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - spring-net

  crud-de-eventos:
    build: ./config-service/crud-de-eventos
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - spring-net

  notification-service:
    build: ./config-service/notification-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
