spring.application.name=config-server
server.port=8288
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/
server.servlet.context-path=/config

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30