name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Test - discovery-server
        run: |
          cd microsservices_esofii/discovery-server
          ./mvnw clean test

      - name: Build & Test - config-server
        run: |
          cd microsservices_esofii/config-server
          ./mvnw clean test

      - name: Build & Test - criar-usuarios
        run: |
          cd config-service/criar-usuarios
          ./mvnw clean test

      - name: Build & Test - crud-de-eventos
        run: |
          cd config-service/crud-de-eventos
          ./mvnw clean test

      - name: Build & Test - notification-service
        run: |
          cd config-service/notification-service
          ./mvnw clean test

      - name: Build Docker images
        run: |
          docker build -t discovery-server ./microsservices_esofii/discovery-server
          docker build -t config-server ./microsservices_esofii/config-server
          docker build -t criar-usuarios ./config-service/criar-usuarios
          docker build -t crud-de-eventos ./config-service/crud-de-eventos
          docker build -t notification-service ./config-service/notification-service
 
