# Server
server.port=8084

# Spring application
spring.application.name=notification-service

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mast3rtask@gmail.com
spring.mail.password=mvbq lhad ydrs mbhd

# JavaMail properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*

# Eureka Client configuration
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# application.properties
spring.cloud.config.enabled=false


eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always



