eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Para que ele tente se conectar ao Eureka em um ambiente de teste
# Outras configurações específicas para o ambiente de teste, se houver
